export const personWords = [
  "Louis Pastuer",
  "Casanova",
  "Ludwig Van Beethoven",
  "Harry Kane",
  "Heston Blumenthal",
  "Jean-Puc Picard",
  "Sergeant Pepper",
  "Keira Knightley",
  "Michael Buble",
  "Princess Leia",
  "Gordon Ramsay",
  "Tiger Woods",
  "Vivaldi",
  "Heston Blumenthal",
  "Manu Vatuvei",
  "Karl Lagerfeld",
  "Confucius",
  "Ozzy Osbourne",
  "Gregg Wallace",
  "Selwyn Toogood",
  "Daniel Craig",
  "Hans Christain Andersen",
  "Anthony Keidis",
  "Barry Manilow",
  "Santa Claus",
  "Peter Hudson",
  "Clint Eastwood",
  "Asterix",
  "Prince",
  "Te Rauparaha",
  "Yves Saint Laurent",
  "Heidi Klum",
  "Cher",
  "Ludwig Van Beethoven",
  "Dave McCartney",
  "Pythagoras",
  "Mahe Drysdale",
  "Sir Douglas Myer",
  "George Lucas",
  "Marilyn Monroe",
  "Dave Dobbyn",
  "Wonder Woman",
  "Galileo",
  "Jean Paul Gaultier",
  "Brian Edwards",
  "Simon Cowell",
  "Chriss Pratt",
  "Lady Gaga",
  "W.C. Fields",
  "Kate Winslet",
  "John F. Kennedy",
  "Elle MacPherson",
  "Pink",
  "Miranda Kerr",
  "Mahatma Gandhi",
  "Georgia Fowler",
  "Kate Moss",
  "Alexander McQueen",
  "The Grinch",
  "Freddie Mecury",
  "George Nepia",
  "Claude Monet",
  "Charles Saatchi",
  "Kanye West",
  "SpongeBob SquarePants",
  "Ernest Hemingway",
  "Jack Lovelock",
  "Leonardo DiCaprio",
  "Kim Kardashian",
  "Crocodile Dundee",
  "Johnny Rotten",
  "Sid Vicious",
  "Andy Murray",
  "Alfred Hitchcock",
  "Elon Musk",
  "Aristotle",
  "The Phantom",
  "Jack Sparrow",
  "Kane Williamson",
  "Gwyneth Paltrow",
  "Kylie Jenner",
  "George Clooney",
  "General Custer",
  "Dame Catherine Tizzard",
  "Des Britten",
  "Justin Timberlake",
  "Leonardo da Vinci",
  "Ed Sheeran",
  "Henry Ford",
  "Brittney Spears",
  "Martin Guptill",
  "Colin Meads",
  "Alexander Graham Bell",
  "Pauline Hanson",
  "Sean Connery",
  "Agatha Christie",
  "Dame Whina Cooper",
  "Sir George Grey",
  "Harry Potter",
  "The Incredible Hulk",
  "Che Fu",
  "Jake 'The Muss'",
  "Theresa May",
  "Madonna",
  "Bruce Willis",
  "Bill Gallagher",
  "Mark Zuckerberg",
  "Paul Holmes",
  "James Bond",
  "Nelson Mandela",
  "Paul McCartney",
  "Joe Vagana",
  "Jack Daniels",
  "Meghan Markle",
  "Paris Hilton",
  "Fred Dagg",
  "James Corden",
  "Ray Woolf",
  "Johnny Walker",
  "Arthur Lydiard",
  "Juliet",
  "Wynton Rufer",
  "The Dalai Lama",
  "Peter Sinclair",
  "Captain James Cook",
  "Danyon Loader",
  "Francis Drake",
  "Michael Joseph Savage",
  "Marc Ellis",
  "Julius Caesar",
  "David Tua",
  "Anne Hathaway",
  "Homer",
  "John Constanble",
  "Ariana Grande",
  "Dame Jenny Gibbs",
  "Bruce Farr",
  "Keith Richards",
  "Captain Kirk",
  "Dr Fred Hollows",
  "Jane Campion",
  "Steve Coogan",
  "Bugs Bunny",
  "Don Brash",
  "Solomone Kata",
];

export const worldWords = [
  "Denmark",
  "The Gaza Strip",
  "The Indian Ocean",
  "Victoria Falls",
  "Auckland",
  "Florida",
  "Oxford",
  "Coventry",
  "The Scottish Highlands",
  "The Ivory Coast",
  "Oman",
  "Manahattan",
  "Glasgow",
  "Auckaland",
  "Whakarewarewa",
  "Czechoslovakia",
  "Noumea",
  "Hanoi",
  "Asia",
  "Dijon",
  "Paddington",
  "Hanmer Springs",
  "Bundaberg",
  "Newfoundland",
  "Myanmar",
  "Mustique",
  "Sandringham",
  "Cambodia",
  "Colombo",
  "The Sahara Desert",
  "Kahurangi National Park",
  "Canberra",
  "Pearl Harbour",
  "The Indian Ocean",
  "Newcastle",
  "Mauritius",
  "France",
  "Beirut",
  "Christmans Island",
  "Cologne",
  "Barcelona",
  "Brazil",
  "Luxembourg",
  "The Bermuda Triangle",
  "Pakistan",
  "Invercargill",
  "Thailand",
  "Texas",
  "California",
  "Sunset Boulevard",
  "St Andrews",
  "Golden Gate Bridge",
  "North Island",
  "Dubai",
  "Raglan",
  "Columbia",
  "Costa Rica",
  "Washington",
  "Tiritiri Matangi Island",
  "Brussels",
  "Hong Kong",
  "Mount Vesuvius",
  "Antarctica",
  "Cambridge",
  "The Aegean Sea",
  "Matakana Island",
  "Tokyo",
  "El Salvador",
  "Great Barrier Island",
  "Northern Ireland",
  "Sydney Harbour Bridge",
  "Gotham City",
  "Mexico",
  "Waitakere Ranges",
  "The Berlin Wall",
  "Marsden Point",
  "The Vatican",
  "Sherwood Forest",
  "Fiordland",
  "Larnach Castle",
  "Miramar",
  "The Bay of Islands",
  "Mozambique",
  "Mount Maunganui",
  "Auckland Town Hall",
  "Venice",
  "Christchurch Catherdral",
  "Gallipoli",
  "Iran",
  "Auckland Ferry Terminal",
  "The Mississippi River",
  "Nigeria",
  "Venezuela",
  "The Stone Store, Kerikeri",
  "Hokitika Gorge",
  "Harvard",
  "Bermuda",
  "Italy",
  "Te Papa",
  "Buenos Aires",
  "Chester",
  "Eden Park",
  "Oxford",
  "Madrid",
  "Cuba Street",
  "Naples",
  "Brighton",
  "Puerto Rico",
  "Paris",
  "Mount Etna",
  "Liverpool",
  "Portugal",
  "Khyber Pass",
  "Pauanui",
  "Iceland",
  "The Louvre",
  "Hot Water Beach",
  "Otago University",
  "Belfast",
  "Tunnel Beach",
  "Croatia",
  "Cathedral Cove",
  "Miranda Hot Springs",
  "Minorca",
  "Crete",
  "Hamilton Gardens",
  "Niagara Falls",
  "Mount Olympus",
  "The Amazon",
  "New York",
  "Chile",
  "Athens",
  "Muriwai Beach",
  "Mount Kilimanjaro",
  "Karangahake Gorge",
  "Mount Rushmore",
  "Wimbledon",
  "Oriental Parade",
  "South Africa",
  "Albert Park",
  "Ascot",
  "Florida",
  "Lebanon",
  "Taranaki",
  "The Pyrenees",
  "Rome",
  "The Zambezi",
];

export const objectsWords = [
  "Signpost",
  "Shopping Bag",
  "Emerald",
  "Sun Lamp",
  "Bow Tie",
  "Hair Dryer",
  "Granule",
  "Sock",
  "Rainbow",
  "Bomb",
  "Nusery",
  "Trout Farm",
  "Microlight",
  "Bow Tie",
  "Lipstick",
  "Ice",
  "iPad",
  "Potato Peeler",
  "Blouse",
  "Wagon",
  "Barbed Wire Fence",
  "iPhone",
  "Screen",
  "Sleeve",
  "Bonfire",
  "Playing Cards",
  "Container",
  "Tea Towel",
  "Van",
  "Antler",
  "Invoice",
  "Dustbin",
  "Bath Tub",
  "Emerald",
  "Give Way Sign",
  "Canoe",
  "Organ",
  "Cable",
  "Buzzy Bee Toy",
  "Tooth Pick",
  "Sheepskin Coat",
  "Shovel",
  "Flax Kete",
  "Bead",
  "Corridor",
  "Rugby Ball",
  "Wand",
  "Sparkler",
  "Halterneck",
  "Ball & Chain",
  "Whisk",
  "Persian Rug",
  "Vase",
  "Ruby",
  "Tube",
  "Tandem",
  "Catalogue",
  "Front Door",
  "Iceblock",
  "Golf Tee",
  "Paper Shredder",
  "Navel",
  "Laser",
  "Grate",
  "Yolk",
  "Ladle",
  "Saddle",
  "Shoe Polish",
  "Letter",
  "Atom",
  "Charcoal",
  "Rusk",
  "Number 8 Wire",
  "Ping Pong Ball",
  "Kennel",
  "Bell",
  "Bunsen Burner",
  "Ballet Shoe",
  "Microchip",
  "Gutter",
  "Leaf Blower",
  "Torch",
  "Paper Aeroplane",
  "Bulb",
  "Shaft",
  "Spiral Staircase",
  "Blanket",
  "Poi",
  "Medicine Ball",
  "Grandmother Clock",
  "Dumpling",
  "Coffee Pot",
  "Scroll",
  "Laundry Basket",
  "Christmas Cracker",
  "Drain",
  "Stone",
  "Matchbox",
  "Removal Van",
  "Reserve Parachute",
  "Fishing Rod",
  "Granule",
  "Cathedral",
  "Fork",
  "Magazine",
  "Cat-flap",
  "Journal",
  "Lock",
  "Launch Pad",
  "Nail-file",
  "Needle",
  "Ferry",
  "Ice Cream Cornet",
  "Bulldog Clip",
  "Wig",
  "Tankard",
  "Match",
  "Hod",
  "Lorry",
  "Stapler",
  "Spear",
  "Funnel",
  "Tank",
  "Watering Can",
  "Grenade",
  "Abattoir",
  "Harp",
  "Lighter",
  "Felt Tip Pen",
  "Sceptre",
  "Paddling Pool",
  "Mineral",
  "Bread Knife",
  "Beach Ball",
  "Milking Shed",
  "Shield",
  "Knickerbocker Glory",
  "Present",
  "Hambuger",
  "Tissue",
  "Hair Dryer",
  "Hamstring",
  "Laptop",
  "Wedge",
  "Aquarium",
  "Loaf",
];

export const actionWords = [
  "Beginning",
  "Inoculating",
  "Chatting",
  "Dousing",
  "Agreeing",
  "Fanning",
  "Absorbing",
  "Winking",
  "Lathering",
];

export const natureWords = [
  "Mackerel",
  "Squid",
  "Pecan",
  "Heather",
  "Newt",
  "Bamboo Shoot",
  "Orange",
  "Deciduous Tree",
  "Angel Fish",
];

export const randomWords = [
  "Game Show",
  "Patent",
  "Genius",
  "Escalator",
  "Triple",
  "Catastrophe",
  "Fortnight",
  "Artery",
  "Errand",
];
