export const personWords = [
  "Louis Pastuer",
  "Casanova",
  "Ludwig Van Beethoven",
  "Harry Kane",
  "Heston Blumenthal",
  "Jean-Puc Picard",
  "Sergeant Pepper",
  "Keira Knightley",
  "Michael Buble",
  "Princess Leia",
  "Gordon Ramsay",
  "Tiger Woods",
  "Vivaldi",
  "Heston Blumenthal",
  "Manu Vatuvei",
  "Karl Lagerfeld",
  "Confucius",
  "Ozzy Osbourne",
  "Gregg Wallace",
  "Selwyn Toogood",
  "Daniel Craig",
  "Hans Christain Andersen",
  "Anthony Keidis",
  "Barry Manilow",
  "Santa Claus",
  "Peter Hudson",
  "Clint Eastwood",
  "Asterix",
  "Prince",
  "Te Rauparaha",
  "Yves Saint Laurent",
  "Heidi Klum",
  "Cher",
  "Ludwig Van Beethoven",
  "Dave McCartney",
  "Pythagoras",
  "Mahe Drysdale",
  "Sir Douglas Myer",
  "George Lucas",
  "Marilyn Monroe",
  "Dave Dobbyn",
  "Wonder Woman",
  "Galileo",
  "Jean Paul Gaultier",
  "Brian Edwards",
  "Simon Cowell",
  "Chriss Pratt",
  "Lady Gaga",
  "W.C. Fields",
  "Kate Winslet",
  "John F. Kennedy",
  "Elle MacPherson",
  "Pink",
  "Miranda Kerr",
  "Mahatma Gandhi",
  "Georgia Fowler",
  "Kate Moss",
  "Alexander McQueen",
  "The Grinch",
  "Freddie Mecury",
  "George Nepia",
  "Claude Monet",
  "Charles Saatchi",
  "Kanye West",
  "SpongeBob SquarePants",
  "Ernest Hemingway",
  "Jack Lovelock",
  "Leonardo DiCaprio",
  "Kim Kardashian",
  "Crocodile Dundee",
  "Johnny Rotten",
  "Sid Vicious",
  "Andy Murray",
  "Alfred Hitchcock",
  "Elon Musk",
  "Aristotle",
  "The Phantom",
  "Jack Sparrow",
  "Kane Williamson",
  "Gwyneth Paltrow",
  "Kylie Jenner",
  "George Clooney",
  "General Custer",
  "Dame Catherine Tizzard",
  "Des Britten",
  "Justin Timberlake",
  "Leonardo da Vinci",
  "Ed Sheeran",
  "Henry Ford",
  "Brittney Spears",
  "Martin Guptill",
  "Colin Meads",
  "Alexander Graham Bell",
  "Pauline Hanson",
  "Sean Connery",
  "Agatha Christie",
  "Dame Whina Cooper",
  "Sir George Grey",
  "Harry Potter",
  "The Incredible Hulk",
  "Che Fu",
  "Jake 'The Muss'",
  "Theresa May",
  "Madonna",
  "Bruce Willis",
  "Bill Gallagher",
  "Mark Zuckerberg",
  "Paul Holmes",
  "James Bond",
  "Nelson Mandela",
  "Paul McCartney",
  "Joe Vagana",
  "Jack Daniels",
  "Meghan Markle",
  "Paris Hilton",
  "Fred Dagg",
  "James Corden",
  "Ray Woolf",
  "Johnny Walker",
  "Arthur Lydiard",
  "Juliet",
  "Wynton Rufer",
  "The Dalai Lama",
  "Peter Sinclair",
  "Captain James Cook",
  "Danyon Loader",
  "Francis Drake",
  "Michael Joseph Savage",
  "Marc Ellis",
  "Julius Caesar",
  "David Tua",
  "Anne Hathaway",
  "Homer",
  "John Constanble",
  "Ariana Grande",
  "Dame Jenny Gibbs",
  "Bruce Farr",
  "Keith Richards",
  "Captain Kirk",
  "Dr Fred Hollows",
  "Jane Campion",
  "Steve Coogan",
  "Bugs Bunny",
  "Don Brash",
  "Solomone Kata",
  "Lionel Messi",
  "Casanova",
  "Rafael Nadal",
  "Ebenezer Scrooge",
  "Hannibal Lector",
  "John Travolta",
  "Sir Peter Snell",
  "Lawrence of Arabia",
  "Frankenstein",
  "Marie Antoinette",
  "Debbie Harry",
  "Goliath",
  "Bob Geldof",
  "Aquaman",
  "Beatrice Faumuina",
  "Graham Norton",
  "John Cleese",
  "Christopher Columbus",
  "Dame Judi Dench",
  "Matthew McConaughey",
  "Hugh Grant",
  "Dalvanius Prime",
  "Hillary Clinton",
  "Shayne Carter",
  "Cleopatra",
  "Dr Suess",
  "Charles Goldie",
  "Peter Burling",
  "Dame Edna Everage",
  "Gregg Chappell",
  "Tom Hanks",
  "Louis Braille",
  "Martin Crowe",
  "Victoria Beckham",
  "ABBA",
  "Justin Beiber",
  "Bad Jelly The Witch",
  "Christopher Robin",
  "Daffy Duck",
  "Helen Clark",
  "Eminem",
  "Tom Cruise",
  "Kate Sheppard",
  "Neil Finn",
  "Sir Ernest Rutherford",
  "Popeye",
  "Mick Jagger",
  "Mickey Mouse",
  "Fred Flinstone",
  "Adele",
  "Cameron Diaz",
  "Jack Nicholson",
  "Anika Moa",
  "Te Kooti",
  "Road Dahl",
  "Miley Cyrus",
  "Hone Heke",
  "Jonah Lomu",
  "Kylie Minogue",
  "David Bowie",
  "Richie McCaw",
  "Lorde",
  "Sonny Bill Williams",
  "Jean Batten",
  "Bruno Lawerence",
  "Alice in Wonderland",
  "Billy T. James",
  "Jemaine Clement",
  "Noah",
  "Michelle Obama",
  "Frank Sinatra",
  "Pat Hanly",
  "Mozart",
  "The Wizard of Oz",
  "Steven Adams",
  "Andy Warhol",
  "Janet Jackson",
  "Stacey Jones",
  "Graeme Brazier",
  "Jacques Cousteau",
  "Bic Runga",
  "Quentin Tarantino",
  "Queen Victoria",
  "Sir Edmund Hillary",
  "Roger Federer",
  "Mussolini",
  "Marco Pierre White",
  "Denzel Washington",
  "Count Dracula",
  "Stacey Jones",
  "Rachel Hunter",
  "Kim Hill",
  "Charles Upham",
  "Peter Pan",
  "J.R.R. Tolkien",
  "Matt Damon",
  "Lewis Carroll",
  "Sir Robert Muldoon",
  "Adam Sandler",
  "Archimedes",
  "Colin McCahon",
  "Charlie Chaplin",
  "Taika Waititi",
  "Captian Scarlet",
  "Napolean Bonaparte",
  "Dr Who",
  "Sherlock Holmes",
  "Nigella Lawson",
  "Sarah Jessica Parker",
  "Andrew Lloyd Webber",
  "Beyonce",
  "Robert De Niro",
  "Harry Styles",
  "Princess Kate",
  "Jacinda Ardern",
  "Paula Bennett",
  "Michael Buble",
  "John Walker",
  "Audret Hepburn",
  "Pharrell Williams",
];

export const worldWords = [
  "Denmark",
  "The Gaza Strip",
  "The Indian Ocean",
  "Victoria Falls",
  "Auckland",
  "Florida",
  "Oxford",
  "Coventry",
  "The Scottish Highlands",
  "The Ivory Coast",
  "Oman",
  "Manahattan",
  "Glasgow",
  "Auckaland",
  "Whakarewarewa",
  "Czechoslovakia",
  "Noumea",
  "Hanoi",
  "Asia",
  "Dijon",
  "Paddington",
  "Hanmer Springs",
  "Bundaberg",
  "Newfoundland",
  "Myanmar",
  "Mustique",
  "Sandringham",
  "Cambodia",
  "Colombo",
  "The Sahara Desert",
  "Kahurangi National Park",
  "Canberra",
  "Pearl Harbour",
  "The Indian Ocean",
  "Newcastle",
  "Mauritius",
  "France",
  "Beirut",
  "Christmans Island",
  "Cologne",
  "Barcelona",
  "Brazil",
  "Luxembourg",
  "The Bermuda Triangle",
  "Pakistan",
  "Invercargill",
  "Thailand",
  "Texas",
  "California",
  "Sunset Boulevard",
  "St Andrews",
  "Golden Gate Bridge",
  "North Island",
  "Dubai",
  "Raglan",
  "Columbia",
  "Costa Rica",
  "Washington",
  "Tiritiri Matangi Island",
  "Brussels",
  "Hong Kong",
  "Mount Vesuvius",
  "Antarctica",
  "Cambridge",
  "The Aegean Sea",
  "Matakana Island",
  "Tokyo",
  "El Salvador",
  "Great Barrier Island",
  "Northern Ireland",
  "Sydney Harbour Bridge",
  "Gotham City",
  "Mexico",
  "Waitakere Ranges",
  "The Berlin Wall",
  "Marsden Point",
  "The Vatican",
  "Sherwood Forest",
  "Fiordland",
  "Larnach Castle",
  "Miramar",
  "The Bay of Islands",
  "Mozambique",
  "Mount Maunganui",
  "Auckland Town Hall",
  "Venice",
  "Christchurch Catherdral",
  "Gallipoli",
  "Iran",
  "Auckland Ferry Terminal",
  "The Mississippi River",
  "Nigeria",
  "Venezuela",
  "The Stone Store, Kerikeri",
  "Hokitika Gorge",
  "Harvard",
  "Bermuda",
  "Italy",
  "Te Papa",
  "Buenos Aires",
  "Chester",
  "Eden Park",
  "Oxford",
  "Madrid",
  "Cuba Street",
  "Naples",
  "Brighton",
  "Puerto Rico",
  "Paris",
  "Mount Etna",
  "Liverpool",
  "Portugal",
  "Khyber Pass",
  "Pauanui",
  "Iceland",
  "The Louvre",
  "Hot Water Beach",
  "Otago University",
  "Belfast",
  "Tunnel Beach",
  "Croatia",
  "Cathedral Cove",
  "Miranda Hot Springs",
  "Minorca",
  "Crete",
  "Hamilton Gardens",
  "Niagara Falls",
  "Mount Olympus",
  "The Amazon",
  "New York",
  "Chile",
  "Athens",
  "Muriwai Beach",
  "Mount Kilimanjaro",
  "Karangahake Gorge",
  "Mount Rushmore",
  "Wimbledon",
  "Oriental Parade",
  "South Africa",
  "Albert Park",
  "Ascot",
  "Florida",
  "Lebanon",
  "Taranaki",
  "The Pyrenees",
  "Rome",
  "The Zambezi",
  "Nicaragua",
  "The Gaza Strip",
  "Takapuna Beach",
  "Seville",
  "Germany",
  "Tongariro National Park",
  "Canterbury",
  "Azerbaijan",
  "The Isle of Wight",
  "Buckingham Palace",
  "Ecuador",
  "Matapouri",
  "Taihape",
  "Red Square",
  "Scotland",
  "Manchester",
  "Hamburg",
  "Tahiti",
  "South Pacific Ocean",
  "Akaroa",
  "The Leaning Tower of Pisa",
  "Spirits Bay",
  "Great Britian",
  "Lisbon",
  "Jamacia",
  "Lake Wanaka",
  "Wueen Charlotte Sound",
  "Tunisia",
  "Ninety Mile Beach",
  "Algeria",
  "Munich",
  "Hastings",
  "Kawarua Beach",
  "Routeburn Track",
  "Fiji",
  "Bordeaux",
  "Malaysia",
  "Stewart Island",
  "Fort Lauderdale",
  "Africa",
  "Waikiki",
  "Los Angeles",
  "Canberra",
  "Ohakune",
  "Argentina",
  "Kaikoura",
  "Quebec",
  "Pacific Ocean",
  "The Falkland Islands",
  "Peking",
  "Pluto",
  "The Panama Canal",
  "Victoria Station",
  "The Gold Coast",
  "Atlantic Ocean",
  "India",
  "The Philippines",
  "Wellington",
  "San Francisco",
  "Kapiti Coast",
  "Los Angeles",
  "St Peter's Square",
  "Nadi",
  "Burgundy",
  "Alaska",
  "Swiss Alps",
  "Tobago",
  "Chicago",
  "Nagasaki",
  "Lithuania",
  "Detroit",
  "Gallipoli",
  "Abbey Road",
  "Ponsonby",
  "Baghdad",
  "Libya",
  "Rio de Janeiro",
  "Apia",
  "Australia",
  "Windsor Castle",
  "St Andrews",
  "Hokianga",
  "Bali",
  "Finland",
  "Le Mans",
  "Monaco",
  "Hawaii",
  "Broadway",
  "United States of America",
  "Cape of Good Hope",
  "Holland",
  "Nelson",
  "Instanbul",
  "Golden Bay",
  "Milan",
  "Johannesburg",
  "Chatham Islands",
  "Cannes",
  "Cambridge",
  "Zambia",
  "Wales",
  "Scott Base",
  "Dijon",
  "Ibizia",
  "St Tropez",
  "The Artic Circle",
  "Loch Ness",
  "Samoa",
  "Nevada Desert",
  "d'Urville Island",
  "Gibraltar",
  "Levin",
  "Opononi",
  "Madagascar",
  "Afghanistan",
  "Treble Cone",
  "St Lucia",
  "Sicily",
  "Downing Street",
  "Palliser Bay",
  "Lake Tekapo",
  "Belgium",
];

export const objectsWords = [
  "Signpost",
  "Shopping Bag",
  "Emerald",
  "Sun Lamp",
  "Bow Tie",
  "Hair Dryer",
  "Granule",
  "Sock",
  "Rainbow",
  "Bomb",
  "Nusery",
  "Trout Farm",
  "Microlight",
  "Bow Tie",
  "Lipstick",
  "Ice",
  "iPad",
  "Potato Peeler",
  "Blouse",
  "Wagon",
  "Barbed Wire Fence",
  "iPhone",
  "Screen",
  "Sleeve",
  "Bonfire",
  "Playing Cards",
  "Container",
  "Tea Towel",
  "Van",
  "Antler",
  "Invoice",
  "Dustbin",
  "Bath Tub",
  "Emerald",
  "Give Way Sign",
  "Canoe",
  "Organ",
  "Cable",
  "Buzzy Bee Toy",
  "Tooth Pick",
  "Sheepskin Coat",
  "Shovel",
  "Flax Kete",
  "Bead",
  "Corridor",
  "Rugby Ball",
  "Wand",
  "Sparkler",
  "Halterneck",
  "Ball & Chain",
  "Whisk",
  "Persian Rug",
  "Vase",
  "Ruby",
  "Tube",
  "Tandem",
  "Catalogue",
  "Front Door",
  "Iceblock",
  "Golf Tee",
  "Paper Shredder",
  "Navel",
  "Laser",
  "Grate",
  "Yolk",
  "Ladle",
  "Saddle",
  "Shoe Polish",
  "Letter",
  "Atom",
  "Charcoal",
  "Rusk",
  "Number 8 Wire",
  "Ping Pong Ball",
  "Kennel",
  "Bell",
  "Bunsen Burner",
  "Ballet Shoe",
  "Microchip",
  "Gutter",
  "Leaf Blower",
  "Torch",
  "Paper Aeroplane",
  "Bulb",
  "Shaft",
  "Spiral Staircase",
  "Blanket",
  "Poi",
  "Medicine Ball",
  "Grandmother Clock",
  "Dumpling",
  "Coffee Pot",
  "Scroll",
  "Laundry Basket",
  "Christmas Cracker",
  "Drain",
  "Stone",
  "Matchbox",
  "Removal Van",
  "Reserve Parachute",
  "Fishing Rod",
  "Granule",
  "Cathedral",
  "Fork",
  "Magazine",
  "Cat-flap",
  "Journal",
  "Lock",
  "Launch Pad",
  "Nail-file",
  "Needle",
  "Ferry",
  "Ice Cream Cornet",
  "Bulldog Clip",
  "Wig",
  "Tankard",
  "Match",
  "Hod",
  "Lorry",
  "Stapler",
  "Spear",
  "Funnel",
  "Tank",
  "Watering Can",
  "Grenade",
  "Abattoir",
  "Harp",
  "Lighter",
  "Felt Tip Pen",
  "Sceptre",
  "Paddling Pool",
  "Mineral",
  "Bread Knife",
  "Beach Ball",
  "Milking Shed",
  "Shield",
  "Knickerbocker Glory",
  "Present",
  "Hambuger",
  "Tissue",
  "Hair Dryer",
  "Hamstring",
  "Laptop",
  "Wedge",
  "Aquarium",
  "Loaf",
  "Diamond",
  "Shopping Bag",
  "Stage",
  "Snake-pit",
  "Halo",
  "Altar",
  "Press",
  "Larder",
  "Spatula",
  "Kiosk",
  "Whip",
  "Warren",
  "Haggis",
  "Wishing Well",
  "Axe",
  "Parking Meter",
  "Bolt",
  "Wingnut",
  "Ledge",
  "Pillow",
  "Pyramid",
  "Jandals",
  "Hob",
  "Microphone",
  "Hood",
  "Teasmaid",
  "Dairy",
  "Clarinet",
  "Biscuit",
  "Blackboard",
  "Ski",
  "Cage",
  "Capsule",
  "Chapel",
  "Tiki",
  "Machete",
  "Scrabble Board",
  "Serviette",
  "Xylophone",
  "Lantern",
  "Bracelet",
  "Fridge Magnet",
  "Lighter",
  "Great Wall of China",
  "Cricket Ball",
  "Pip",
  "Gag",
  "Headphones",
  "Dodgem Car",
  "Mug",
  "Bullet",
  "Crib",
  "Spanner",
  "Lazy Susan",
  "Ammunition",
  "Light Switch",
  "Fountain",
  "Bar of Soap",
  "Fire Alarm",
  "Contact Lenses",
  "Poster",
  "Cricket Bat",
  "Tablet",
  "Corner",
  "Bagpipes",
  "Tomato Sauce",
  "Beach House",
  "Mannequin",
  "Microwave",
  "Vacuum Cleaner",
  "Licence",
  "Suitcase",
  "Stick of Dynamite",
  "Umbrella",
  "Shotgun",
  "Scoreboard",
  "Voucher",
  "Ruler",
  "Roof",
  "Noose",
  "Hot Cross Bun",
  "Yacht",
  "First Aid Kit",
  "Beard",
  "Candy Floss",
  "Snare",
  "Dimple",
  "Atlas",
  "Marae",
  "Boulder",
  "Pair of Tweezers",
  "Wok",
  "Dog Basket",
  "Snowman",
  "G String",
  "Portrait",
  "Catapult",
  "Kiwifruit",
  "Merino Wool",
  "Igloo",
  "Wine Glass",
  "Mask",
  "Vitamin Pill",
  "Tractor",
  "School Hall",
  "Cellar",
  "Drone",
  "Lance",
  "Circus",
  "Sack",
  "Picnic Hamper",
  "Rollerskates",
  "Duvet",
  "Noodle",
  "BMX Bike",
  "Notice Board",
  "Jumper",
  "Label",
  "Toothbrush",
  "Rainbow",
  "Cave",
  "Gumboots",
];

export const actionWords = [
  "Beginning",
  "Inoculating",
  "Chatting",
  "Dousing",
  "Agreeing",
  "Fanning",
  "Absorbing",
  "Winking",
  "Lathering",
  "Watching",
  "Connecting",
  "Halting",
  "Contrasting",
  "Agreeing",
  "Bungling",
  "Multiplying",
  "Congratulating",
  "Embezzling",
  "Confiscating",
  "Weaving",
  "Burying",
  "Yapping",
  "Approving",
  "Fancying",
  "Glistening",
  "Carrying",
  "Burning",
  "Batting",
  "Blazing",
  "Stealing",
  "Fleecing",
  "Prancing",
  "Galloping",
  "Chatting",
  "Hurding",
  "Hugging",
  "Hooking",
  "Aching",
  "Crossing",
  "Exluding",
  "Steadying",
  "Bending",
  "Trotting",
  "Confessing",
  "Dripping",
  "Drawing",
  "Striking",
  "Kicking",
  "Torturing",
  "Expecting",
  "Exerting",
  "Hunting",
  "Corrupting",
  "Choking",
  "Varnishing",
  "Kidding",
  "Sampling",
  "Impaling",
  "Gallivanting",
  "Correcting",
  "Salivating",
  "Stitching",
  "Entailing",
  "Twisting",
  "Implementing",
  "Congesting",
  "Studying",
  "Bustling",
  "Capturing",
  "Explaining",
  "Burrowing",
  "Piercing",
  "Cantering",
  "Mowing",
  "Signing",
  "Limping",
  "Struggling",
  "Launching",
  "Hurdling",
  "Consuming",
  "Controlling",
  "Juggling",
  "Overflowing",
  "Boiling",
  "Blushing",
  "Aspiring",
  "Cycling",
  "Conserving",
  "Guzzling",
  "Heaving",
  "Brushing",
  "Fondling",
  "Disconnecting",
  "Bumbling",
  "Contravening",
  "Consulting",
  "Dancing",
  "Fielding",
  "Drizzling",
  "Holding",
  "Constraining",
  "Lamenting",
  "Absorbing",
  "Whispering",
  "Absolving",
  "Undressing",
  "Pacing",
  "Jeopardising",
  "Proving",
  "Probing",
  "Arguing",
  "Charging",
  "Laughing",
  "Singing",
  "Intending",
  "Fretting",
  "Failing",
  "Angling",
  "Picketing",
  "Dropping",
  "Glimpsing",
  "Blowing",
  "Shining",
  "Electing",
  "Cleansing",
  "Howling",
  "Aiming",
  "Cornering",
  "Hailing",
  "Expiring",
  "Walking",
  "Existing",
  "Quickening",
  "Whistling",
  "Sprinting",
  "Abiding",
  "Extending",
  "Expressing",
  "Conning",
  "Breathing",
  "Broadcasting",
  "Fanning",
  "Assisting",
  "Insulating",
  "Brewing",
  "Advocating",
  "Moaning",
  "Conducting",
  "Inoculating",
  "Canvassing",
  "Limbering Up",
  "Swimming",
  "Haemorrhaging",
  "Evaluating",
  "Snoring",
  "Kissing",
  "Hitchhiking",
  "Consolidating",
  "Abolishing",
  "Adopting",
  "Yodelling",
  "Heating",
  "Happening",
  "Canoeing",
  "Co-ordinating",
  "Wheezing",
  "Inspiring",
  "Jousting",
  "Gleaming",
  "Insulting",
  "Eating",
  "Threatening",
  "Travelling",
  "Confiding",
  "Immigrating",
  "Employing",
  "Texting",
  "Absconding",
  "Carving",
  "Contacting",
  "Coughing",
  "Hatching",
  "Cooking",
  "Washing",
  "Rebelling",
  "Thinking",
  "Twitching",
  "Booking",
  "Fasting",
  "Havling",
  "Grating",
  "Lying",
  "Continuing",
  "Repeating",
  "Leaving",
  "Approaching",
  "Hyperventilating",
  "Smoking",
  "Chasing",
  "Applying",
  "Colliding",
  "Cutting",
  "Grimacing",
  "Hoping",
  "Crying",
  "Grabbing",
  "Floating",
  "Labelling",
  "Brooding",
  "Sailing",
  "Laying",
  "Stalling",
  "Collapsing",
  "Belittling",
  "Trying",
  "Voting",
  "Parachuting",
  "Beckoning",
  "Sleeping",
  "Enduring",
  "Dying",
  "Simmering",
  "Illustrating",
  "Confusing",
  "Jumping",
  "Lathering",
  "Combing",
  "Buttoning",
  "Performing",
  "Grading",
  "Admitting",
  "Browsing",
  "Driving",
  "Numbering",
  "Catching",
  "Instructing",
  "Flossing",
  "Bedragging",
  "Bowling",
  "Throwing",
  "Fighting",
  "Blinking",
  "Intervieiwing",
  "Exploding",
  "Reporting",
  "Earning",
  "Accommodating",
  "Adoring",
  "Feeding",
  "Judging",
  "Gobbling",
  "Strumming",
  "Blocking",
  "Altering",
  "Draining",
  "Balancing",
  "Softening",
  "Hounding",
  "Co-operating",
  "Congregatting",
  "Harmonizing",
  "Bombing",
  "Timing",
  "Naming",
  "Sweeping",
  "Bounding",
  "Chipping",
  "Arranging",
  "Yawning",
];

export const natureWords = [
  "Mackerel",
  "Squid",
  "Pecan",
  "Heather",
  "Newt",
  "Bamboo Shoot",
  "Orange",
  "Deciduous Tree",
  "Angel Fish",
  "Rice",
  "Kea",
  "Salmon",
  "Pine Cone",
  "Pohutukawa",
  "Coffee",
  "Tuatara",
  "Tsunami",
  "Calf",
  "Daisy",
  "Vine",
  "Tyrannosaurus Eex",
  "Cockle",
  "Crab",
  "Centipede",
  "Virus",
  "Earwig",
  "Truffle",
  "Glade",
  "Fig",
  "Whelk",
  "Brown Skink",
  "Lancewood",
  "Stag",
  "Wetland",
  "Vulture",
  "Grass",
  "Cat",
  "Sloth",
  "Jasmine",
  "Flea",
  "Marrow",
  "Hamilton's Frog",
  "Green Gecko",
  "Labrador",
  "Dill",
  "Peanut",
  "Worm",
  "White Heron",
  "Raven",
  "Cactus",
  "Ginger Root",
  "Olive",
  "Tiger",
  "Parrot",
  "Anaconda",
  "Blackcurrant",
  "Tulip",
  "Takahe",
  "Moth",
  "Albatross",
  "Deer",
  "Pumpkin",
  "Apricot",
  "Raspberry",
  "Peacock",
  "Humpback Whale",
  "Dragonfly",
  "Quail",
  "Rose",
  "Bottlenose Dolphin",
  "Kangaroo",
  "Cocoon",
  "Monarch Butterfly",
  "Jackal",
  "Elephant Seal",
  "Komodo Dragon",
  "Aubergine",
  "Panther",
  "Flying Squirrel",
  "Seaweed",
  "Hen",
  "Skunk",
  "Palm Tree",
  "Cane Toad",
  "Thrush",
  "Flying-fish",
  "Sparrow",
  "Baboon",
  "Polar Bear",
  "Rock Pool",
  "Python",
  "Cheetah",
  "Crustacean",
  "Seal",
  "Whitebait",
  "Mosquito",
  "Thermal Hot Pool",
  "Silkworm",
  "Swede",
  "Bantam",
  "Snake",
  "Poodle",
  "Orange",
  "Crocodile",
  "Sea Horse",
  "Moray Eel",
  "Frost",
  "Scallop",
  "Piper",
  "Violet",
  "Lychee",
  "Weta",
  "Swamp",
  "Stork",
  "Marlin",
  "Oak Tree",
  "Magpie",
  "Clam",
  "Brown Trout",
  "Wheat",
  "Kiwi Fruit",
  "Creek",
  "Paua",
  "Glacier",
  "Snowdrop",
  "Hoki",
  "Sheep",
  "Gooseberry",
  "Woodpecker",
  "Gum Tree",
  "Stingray",
  "Lime Tree",
  "Paddle Crab",
  "Porcupine",
  "Plankton",
  "Rattlesnake",
  "Carrot",
  "Albacore Tuna",
  "Blackberry",
  "Pacific Oysters",
  "Mullet",
  "Bamboo Shoot",
  "Caterpillar",
  "Skate",
  "Buttercup",
  "Falcon",
  "Penguin",
  "Goldfish",
  "Squid",
  "Bull",
  "Chimpanzee",
  "Sand",
  "Primate",
  "Lettuce",
  "Fungus",
  "Gannet",
  "Butterfly",
  "Gunnard",
  "Reed",
  "Weevil",
  "Water Lily",
  "Kale",
  "Cloud",
  "Conifer",
  "Blueberry",
  "Quinoa",
  "Dolphin",
  "Sow",
  "Gale Force",
  "Hebe",
  "Parrotfish",
  "Poppy",
  "Birch Tree",
  "Jersey Crow",
  "Shark",
  "Climate Change",
  "Insect",
  "Bean Sprout",
  "Maple Tree",
  "Gibbon",
  "Strawberry",
  "Whale",
  "Lizard",
  "Mushroom",
  "Huhu Beetle",
  "Weka",
  "Watermelon",
  "Deer",
  "Boar",
  "Cockroach",
  "Tui",
  "Wolf",
  "Turtle",
  "Hedgehod",
  "Avocado",
  "Ostrich",
  "Hammerhead Shark",
  "Pansy",
  "Chihuahau",
  "Spider",
  "Kauri Tree",
  "Swan Plant",
  "Bacteria",
  "Feijoa",
  "Blue Penguin",
  "Kina",
  "Camel",
  "Ponga Tree",
  "Cotton",
  "Hydrangea",
  "Guinea Pig",
  "Piglet",
  "Anteater",
  "Panda",
  "Kiwi",
  "Sage",
  "Totara Tree",
  "Trout",
  "Lemon",
  "Cygnet",
  "Adder",
  "Leopard",
  "Snail",
  "Holly",
  "Boa Constricter",
  "Chicken",
  "Mako Shark",
  "Nikau",
  "Tree",
  "Kowhai",
  "Hay",
  "Blue Cod",
  "Flounder",
  "Pelican",
  "Zebra",
  "Pine Tree",
  "Southern Cross",
  "Pea",
  "Toi Toi",
  "Cashew Nut",
  "Garlic",
  "Mould",
  "Oak",
  "Pineapple",
  "Reindeer",
  "Prawn",
  "Squirrel",
  "Marigold",
  "Walnut",
  "Shark",
  "Terakihi",
  "Frog",
  "Snapper",
  "Gecko",
  "Gannet",
  "Stallion",
  "Rabbit",
  "Jellyfish",
  "Cuckoo",
  "Stick Insect",
  "Puppy",
  "Pigeon",
  "Rhinoceros",
  "Kumara",
  "Stingray",
  "Venus Fly Trap",
  "Jaguar",
  "Kereru",
  "Kahawai",
];

export const randomWords = [
  "Game Show",
  "Patent",
  "Genius",
  "Escalator",
  "Triple",
  "Catastrophe",
  "Fortnight",
  "Artery",
  "Errand",
  "Haere Mai",
  "Kaumatua",
  "Orchestra",
  "Checkmate",
  "Triple",
  "Horoscope",
  "Horizon",
  "Banquet",
  "Six60",
  "Expedition",
  "Selective",
  "Arithmetic",
  "Bling",
  "Acrobat",
  "Conference",
  "Cosmetic",
  "Merchandise",
  "Magistrate",
  "Mana",
  "Tapu",
  "Sanctuary",
  "Waste",
  "Netflix",
  "Furniture",
  "Genius",
  "Courteous",
  "Tamariki",
  "Outlaw",
  "Psychic",
  "YouTube",
  "Zinc",
  "Articulate",
  "Weight",
  "Accomplice",
  "Ethopia",
  "Opposite",
  "Thrust",
  "Signature",
  "Ability",
  "Alright",
  "Bach",
  "Pepper",
  "Code",
  "Ballroom Dancing",
  "Baked Beans",
  "Aristocracy",
  "Fluke",
  "Samsung",
  "Acoustic Guitar",
  "eBay",
  "The Statue of Liberty",
  "Abrasive",
  "Hapu",
  "Idle",
  "Horizontal",
  "Boxing Day Races",
  "Anorexia",
  "The Sky Tower",
  "Exempt",
  "Depature",
  "Chardonnay",
  "Illusion",
  "Bias",
  "Sky's the Limit",
  "Cafe",
  "Abnormal",
  "Vodka",
  "Beeline",
  "Cheeky",
  "Illegitimate",
  "Knees Up",
  "Spotify",
  "Instalment",
  "The Beehive",
  "Assume",
  "Clockwork",
  "Waiata",
  "100 Metres",
  "Nothern Hemishpere",
  "Godzone",
  "Dole",
  "Cook Strait Ferry",
  "Bunk",
  "Laundry",
  "Impatient",
  "Space Invaders",
  "Alien",
  "Aussie",
  "Opium",
  "Accident",
  "Text",
  "Accuracy",
  "Achievement",
  "Fortnight",
  "Incessant",
  "Bluff",
  "Caravan",
  "Cocktail",
  "Crockpot",
  "Shearing Shed",
  "Ulimate",
  "Dragon",
  "Comic",
  "Pisces",
  "Trail Mix",
  "Meticulous",
  "Fluff",
  "X-Ray",
  "Puku",
  "Width",
  "Accent",
  "Pavlova",
  "Determination",
  "Umpire",
  "Teeth",
  "Indicator",
  "Hostess",
  "Generic",
  "Groom",
  "Pakeha",
  "Crucial",
  "Speed Limit",
  "Campus",
  "X-Factor",
  "Pegassu",
  "Medical",
  "Lineout",
  "Dag",
  "Wahine",
  "Frame",
  "Smoko",
  "Catastrophe",
  "Couple",
  "Knob",
  "Muppet",
  "Cause",
  "Aroha",
  "Gin",
  "Patent",
  "Barefoot",
  "Gracious",
  "Powhiri",
  "Strategy",
  "Contigingency",
  "Carbon",
  "Inheritance",
  "Snob",
  "The Treaty of Waitangi",
  "Carbohydrate",
  "Capsize",
  "Costly",
  "Exploration",
  "Evidently",
  "Ugly",
  "Geriatric",
  "Acrobatic",
  "Diabetes",
  "Cement",
  "Hard Case",
  "Twitter",
  "Club Sandwich",
  "FaceTime",
  "Snapchat",
  "Give Way Sign",
  "Unanimous",
  "Ad Lib",
  "Cocktail Shaker",
  "Council",
  "SuperGold Card",
  "Situation",
  "Succulent",
  "Light Bulb",
  "Rythm",
  "Above",
  "Magic",
  "Chronic",
  "Bunch",
  "Chronological",
  "Whanau",
  "Geometry",
  "Explination",
  "Nana",
  "Injunction",
  "Whisky",
  "Manager",
  "Tiki Tour",
  "Prefect",
  "Suction",
  "Boredom",
  "Belly Button Fluff",
  "Economy",
  "Treaty of Waitangi",
  "Adhesive",
  "Immense",
  "Flourescent",
  "Florist",
  "Hall of Fame",
  "Despite",
  "Smug",
  "Ethical",
  "Hour",
  "Botox",
  "Undercover",
  "Exit",
  "Ego",
  "Democracy",
  "Sacrificial",
  "Absolute",
  "Initiating",
  "Across The Ditch",
  "Immunity",
  "Peanut Slab",
  "Instagram",
  "Snowman",
  "Independent",
  "Errand",
  "Pretty",
  "Chapter",
  "Essential",
  "Kia Ora",
  "Backgammon",
  "Betrayal",
  "Income",
  "Conscience",
  "Ring the Bell",
  "Sulphuric Acid",
  "Antiperspirant",
  "Catalyst",
  "Exactly",
  "Belonging",
  "Despicable",
  "Gradual",
  "Consecutive",
  "Innocent",
  "Theory",
  "Barren",
  "Hospitality",
  "Influx",
  "Croquet",
  "Gruesome",
  "Moa",
  "Acupuncutre",
  "Integrity",
  "Espionage",
  "Emotion",
  "Bible",
  "Action Replay",
  "Fat Freddy's Drop",
  "Tattoo",
  "Heir",
  "Overweight",
  "Hello Sailor",
  "Hint",
  "Petrol",
  "Half Marathon",
  "e-ticket",
  "Dyslexia",
  "Siamese Twins",
  "Bonus",
];
